function dwot_draw_hog_bounding_box(hogVIdx1, hogUIdx1, hogVIdx2, hogUIdx2, hogSizeInPixel)

rectangle('position', [hogVIdx1 - 1, hogUIdx1 - 1, hogVIdx2-hogVIdx1 + 1, hogUIdx2-hogUIdx1 + 1] * hogSizeInPixel,...
        'LineWidth',3,...
        'EdgeColor','w');